on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@release-1.0.2
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "PackageAware/dast-github-actions-cloud"
          scan_mode: "baseline"
          api_url: "https://qa-api.soos.io/api/"
          target_url: "https://brokencrystals.com/"
          sarif: true
          gpat: ${{ secrets.SOOS_GPAT }}
